ConnectSample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ConnectSample.ViewModels;
using ConnectSample.Models;

namespace ConnectSample.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			if (Session["User"] == null)
				return RedirectToAction("Login");

			var user = Session["User"] as User;
			var tripDigestList = Trip.GetTripDigest(user);
			Session["TripDigestList"] = tripDigestList;

			return View(tripDigestList);


		}

		public ActionResult About()
		{
			ViewBag.Message = "Your app description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}

		[HttpGet]
		[AllowAnonymous]
		public ActionResult Login(string returnUrl)
		{
			ViewBag.ReturnUrl = returnUrl;
			return View();
		}

		[HttpPost]
		[AllowAnonymous]
		[ValidateAntiForgeryToken]
		public ActionResult Login(User model, string returnUrl)
		{
			ViewBag.Message = "Login to your account";

			if (!model.Load())
			{
				Session.Add("IsAuthenticated", "false");
				ViewData.Add(new KeyValuePair<string, object>("LoginError", "Login not found !!"));
				return View(model);
			}

			Session.Add("IsAuthenticated", "true");
			Session.Add("User", model);
			if (model.IsLinkedToConcur)
			{
				Session.Add("IsLinkedToConcur", "true");
			}

			return RedirectToAction("Index");
		}

		[HttpGet]
		[AllowAnonymous]
		public ActionResult Register()
		{
			return View();
		}


		[HttpPost]
		[AllowAnonymous]
		[ValidateAntiForgeryToken]
		public ActionResult Register(User model, string returnUrl)
		{
			ViewBag.Message = "Register for a new account";

			model.Save();
			Session.Add("IsAuthenticated", "true");
			Session.Add("User", model);

			return RedirectToAction("Index");
		
		}

		[HttpGet]
		public ActionResult Link()
		{
			if (Session["User"] == null)
				return RedirectToAction("Login");

			var user = Session["User"] as User;
			user.Load();
			
			return View(user);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Link(User model, string returnUrl)
		{
			ViewBag.Message = "Link to your Concur account";
			if (Session["User"] == null)
				return RedirectToAction("Login");

			model.LinkToConcur();
			model.SubscribeToChanges("profile");
			model.SubscribeToChanges("itinerary");

			model.Save();
			Session["User"] = model;

			if (model.IsLinkedToConcur)
				Session.Add("IsLinkedToConcur", "true");

			return View(model); 

		}

		//[ValidateAntiForgeryToken]
		public ActionResult UnLink()
		{
			if (Session["User"] == null)
				return RedirectToAction("Login");

			User model = Session["User"] as User;
			model.UnLinkToConcur();
			Session.Add("IsLinkedToConcur", "false");

			return RedirectToAction("Manage");
		}

		[HttpGet]
		[AllowAnonymous]
		public ActionResult Manage()
		{
			if (Session["User"] == null)
				return RedirectToAction("Login");

			var model = Session["User"] as User;
			return View(model);
		}
	}
}

ConnectSample/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ConnectSample.ViewModels;
using ConnectSample.Models;

namespace ConnectSample.Controllers
{
    public class TripController : Controller
    {
		public ActionResult Index(long Id)
		{
			if (Session["User"] == null)
				return RedirectToAction("Login", "Home");

			var user = Session["User"] as User;
			if (Session["TripDigestList"] == null)
				throw new ApplicationException("Error finding the trip specified. Please refresh and try again.");


			List<TripDigestViewModel> tripDigestList = Session["TripDigestList"] as List<TripDigestViewModel>;
			TripDigestViewModel tripSelected = tripDigestList.Where<TripDigestViewModel>(t => t.TripId == Id).FirstOrDefault();
			if (tripSelected == null)
				throw new ApplicationException("Error finding the trip specified. Please refresh and try again.");

			TripViewModel model = Trip.GetTrip(user, tripSelected);
			model.LoadDestinationData();

			return View(model);
		}

    }
}

ConnectSample/Views/Home/About.cshtml
@{
	ViewBag.Title = "ConnectLocal";
	ViewBag.Message = "Get Local using Connect !!";
}

<hgroup class="title">
	<h2>@ViewBag.Message</h2>
</hgroup>

<article>
@section featured {
	<section class="featured">
		<div class="content-wrapper">
			<hgroup class="title">
				<h1>@ViewBag.Title.</h1>
				<h2>@ViewBag.Message</h2>
			</hgroup>
			<p>
				ConnectLocal is your gateaway to view local information about your destination before you get there.
			</p>
			<p>
				To learn more about Connect Platform visit
				<a href="https://developer.concur.com/" title="Concur Connect">https://developer.concur.com/</a>.
				The page features <mark>videos, tutorials, and samples</mark> to help you get the most from Concur Connect Platform.
				If you have any questions about Connect Platform contact
				<a href="https://developer.concur.com/en-us/support" title="Connect Support">our support team</a>.
			</p>
		</div>
	</section>
}

<h3>We suggest the following:</h3>
<ol class="round">
	<li class="one">
		<h5>Getting Started</h5>
		Register for a free ConnectLocal account and link it your Sandbox account. If you do not have a Concur Sandbox you can get one <a href="https://developer.concur.com/register">here</a>. See how the use of Connect Platform and API allows you to use the traveler's trips and information.
		<a href="https://developer.concur.com/api-documentation/web-services/itinerary">Learn more…</a>
	</li>

	<li class="two">
		<h5>Review sample code</h5>
		This application provides sample code using github to demonstrate how to build your own applications using Connect API. The APIs used in this sample are - Itinerary, Travel Profile and ExpenseCapture. The sample code is available <a href="https://github.com/amolkasbekar/ConnectLocal">here</a> on github. This code here is meant only as a guidance and is not meant to use as-is.
	</li>

	<li class="three">
		<h5>Questions</h5>
		For questions regarding this app or the code on github, contact <a href="mailto:amol.kasbekar@concur.com">Amol Kasbekar</a>. For all other generic questions please contact <a href="https://developer.concur.com/en-us/support">Connect support</a> team.
	</li>
</ol>
</article>

<aside>
	<ul>
		<li>@Html.ActionLink("Home", "Index", "Home")</li>
		<li>@Html.ActionLink("About", "About", "Home")</li>
		<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
		<li>@Html.ActionLink("Your Account", "Manage", "Home")</li>
	</ul>
</aside>

ConnectSample/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.702.8828</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">ConnectSupport@concur.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">ConnectMarketing@concur.com</a></span>
    </p>
    <p>
        <span class="label">Technical:</span>
        <span><a href="mailto:amol.kasbekar@concur.com">amol.kasbekar@concur.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        209 Madison Street<br />
        Alexandria, VA 22314
    </p>
</section>

ConnectSample/Views/Home/Index.cshtml
@model List<ConnectSample.ViewModels.TripDigestViewModel>

@{
	ViewBag.Title = "Your upcoming trip list";
}

@if (Model.Count == 0)
{
	<h3>You have no upcoming trips. </h3>
	<h4>Verify that your account is linked to Concur.</h4>
	<br />
	<br />
	<br />
	<text>When you're safe at home you wish you were having an adventure; when you're having an adventure you wish you were safe at home. - <i> Thronton Wilder </i></text>
}
else
{ 
	<h3>Your upcoming trip list:</h3>
	<p>
		<table class="triplist">
			<thead>
				<tr>
					<th class="triplist" scope="col">Trip Name</th>
					<th class="triplist" scope="col">Description</th>
					<th class="triplist" scope="col">Start Date</th>
					<th class="triplist" scope="col">End Date</th>
					<th class="triplist" scope="col"></th>
				</tr>
				</thead>
		@foreach (ConnectSample.ViewModels.TripDigestViewModel trip in Model)
		{ 
			<tr>
				<td class="triplist"><div class="tripname">@trip.TripName </div></td>
				<td class="triplist"><div class="tripdescription">@trip.Description</div></td>
				<td class="triplist">@trip.StartDateLocal.ToShortDateString()</td>
				<td class="triplist">@trip.EndDateLocal.ToShortDateString()</td>
				<td class="triplist">@Html.ActionLink("View Local Info for the trip", "Index", "Trip",  new {Id=trip.TripId }, null)</td>
			</tr>
		}
		</table>
	</p>
	<br />
	<br />
	<text>
		You can never go home again, but the truth is you can never leave home, so it's all right. -  <i>Maya Angelou</i>
	</text>
}

ConnectSample/Views/Home/Link.cshtml
@model ConnectSample.Models.User

@{
	ViewBag.Title = "Links your Concur accounts with Sample App.";
}

<hgroup class="title">
	<h1>@ViewBag.Title</h1>
</hgroup>

<br />
<br />
<section id="loginForm">

@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
	@Html.ValidationSummary(true)
	
	string userName = this.Model.UserName;
	//if (Session["IsLinkedToConcur"] == null || Session["IsLinkedToConcur"] != "true")
	if (!Model.IsLinkedToConcur)
	{ 
		<fieldset>
			@Html.HiddenFor(m => m.UserName)
			<text>Hello <b>@userName</b> enter your Concur account details here: </text>
			<ol>
				<li>
					@Html.LabelFor(m => m.ConcurUserName)
					@Html.TextBoxFor(m => m.ConcurUserName)
					@Html.ValidationMessageFor(m => m.ConcurUserName)
				</li>
				<li>
					@Html.LabelFor(m => m.ConcurPassword)
					@Html.PasswordFor(m => m.ConcurPassword)
					@Html.ValidationMessageFor(m => m.ConcurPassword)
				</li>
			</ol>
			@Html.AntiForgeryToken()
			<input type="submit" value="Link" />
		</fieldset>	
	}
	else
	{ 
		<text>Hello <b>@userName</b> congratulations your account is linked to Concur </text>
		<ul>
			<li>
				<b>OAuth Token: </b> @Html.DisplayTextFor(m => m.OAuthToken.Token)
			</li>
			<li>
				<b>Expiration :  </b> @Html.DisplayTextFor(m => m.OAuthToken.ExpirationDate)
			</li>
		</ul>
	 
	}
}
</section>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

ConnectSample/Views/Home/Login.cshtml
@model ConnectSample.Models.User

@{
    ViewBag.Title = "Login to ConnectLocal";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

<h3>

</h3>
<section id="loginForm">
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </li>
        </ol>
		@Html.AntiForgeryToken()
        <input type="submit" value="Log in" />
    </fieldset>
}
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConnectSample/Views/Home/Manage.cshtml
@model ConnectSample.Models.User

@{
	ViewBag.Title = "Manage your ConnectLocal account";
}


Hello <b>@Model.UserName</b> you can link/delink your Concur account from this page.
<br />
@{
	@Html.AntiForgeryToken()

	if (!Model.IsLinkedToConcur)
	{ 
		<text>Your account is <b>not linked</b> to Concur.</text>
		@Html.ActionLink("Link", "Link")
	}
	else
	{
		<text>Your account is already <b>linked</b> to Concur. </text>
		@Html.ActionLink("UnLink", "UnLink")
	}


}

ConnectSample/Views/Home/Register.cshtml
@model ConnectSample.Models.User
@{
    ViewBag.Title = "Register";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>Create a new account.</h2>
</hgroup>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
            </li>
			<li>
				@Html.Label("ConfirmPassword")

				@*Todo add validation *@
				@Html.Password("ConfirmPassword");
			</li>
        </ol>
        <input type="submit" value="Register" />
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConnectSample/Views/Home/TripDetails.cshtml
@{
    ViewBag.Title = "TripDetails";
}

<h2>TripDetails</h2>